### ISSUE TITLE
Add sponsor

### ISSUE THREAD

**Issue by syedjawadakhtar** [auvzhcet/auvzhcet_web#23]
New sponsor was added on 2 February  2020 (Check Instagram post regarding this: [https://www.instagram.com/p/B8EG6KWgcaQ/?igshid=h06hnp6tx8qd](https://www.instagram.com/p/B8EG6KWgcaQ/?igshid=h06hnp6tx8qd)).
Enquire about the price discounted with the Chairperson and classify it into the correct sponsorship category - Silver or Bronze?

**Comment by yash1412** [comment]
I am working on this issue.
