### ISSUE TITLE
Update recent news

### ISSUE THREAD

**Issue by syedjawadakhtar** [auvzhcet/auvzhcet_web#28]
1. Update events with recent JMI webinar and **Upcoming event** of inaugural
2. Update Instagram post with recent milestone posted there

**Comment by pnijhara** [comment]
@aqdasak

**Comment by aqdasak** [comment]
>     2. Update Instagram post with recent milestone posted there
Should we skip this as there is another issue to replace instagram: Issue 38 [Replace facebook feeds with insta post](https://github.com/auvzhcet/auvzhcet_web/issues/38)

**Comment by pnijhara** [comment]
Or you can solve both the issues in a single PR.
