### ISSUE TITLE
Rename MATE-ROV as MTS-AUVZHCET

### ISSUE THREAD

**Issue by pnijhara** [auvzhcet/auvzhcet_web#39]

**Comment by shubh2001** [comment]
in the NavBar? @pnijhara

**Comment by pnijhara** [comment]
Both in Nav-Bar and its corresponding page.
Replace MATE-ROV with MTS-AUVZHCET.

**Comment by shubh2001** [comment]
should I replace it in the paragraph as well ? @pnijhara

**Comment by pnijhara** [comment]
Remove the last paragraph regarding mate rov.
We need to focus only on mts
