### ISSUE TITLE
Add Github link in footer

### ISSUE THREAD

**Issue by syedjawadakhtar** [auvzhcet/auvzhcet_web#47]
Github link to https://github.com/auvzhcet/ on Contacts page, Alongside other SMs.

**Comment by pnijhara** [comment]
IMHO Instead of adding GitHub link in the contacts section, it should be placed in the footer of the website!

**Comment by syedjawadakhtar** [comment]
> IMHO Instead of adding GitHub link in the contacts section, it should be placed in the footer of the website!

True that! I meant the footer. 
I won't be able access my laptop till Monday, so please proceed with the changes required.

**Comment by pnijhara** [comment]
@aqdasak please update the link in the footer!
